version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - projreact_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    networks:
      - projreact_network

networks:
  projreact_network:
    driver: bridge
